#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_LiufangzheCommon

#include "Basic.hpp"

#include "KuroAnim_structs.hpp"
#include "Engine_structs.hpp"
#include "ELiufangzheWeaponType_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ABP_MonsterCommon_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_LiufangzheCommon.ABP_LiufangzheCommon_C
// 0x5620 (0x84B0 - 0x2E90)
class UABP_LiufangzheCommon_C : public UABP_MonsterCommon_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_ABP_LiufangzheCommon_C;             // 0x2E88(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_1_ABP_LiufangzheCommon_C;       // 0x2E90(0x0038)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_ABP_LiufangzheCommon_C; // 0x2EC8(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_ABP_LiufangzheCommon_C; // 0x2EE8(0x0020)()
	struct FAnimNode_Feedback                     AnimGraphNode_Feedback_ABP_LiufangzheCommon_C;     // 0x2F08(0x0268)()
	struct FAnimNode_SightLock                    AnimGraphNode_SightLock_ABP_LiufangzheCommon_C;    // 0x3170(0x01C0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_ABP_LiufangzheCommon_C; // 0x3330(0x0138)()
	struct FAnimNode_BoneRotateToLocation         AnimGraphNode_BoneRotateToLocation_ABP_LiufangzheCommon_C; // 0x3468(0x0128)()
	struct FAnimNode_Root                         AnimGraphNode_Root_ABP_LiufangzheCommon_C;         // 0x3590(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_44;                 // 0x35C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x35F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x3618(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x3640(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x3668(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x3690(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x36B8(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x36E8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_67;                   // 0x3720(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_66;                   // 0x37B0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_65;                   // 0x3840(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_64;                   // 0x38D0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_63;                   // 0x3960(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_62;                   // 0x39F0(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_7;                    // 0x3A80(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x3B30(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3_ABP_LiufangzheCommon_C; // 0x3B68(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x3B98(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x3BD0(0x0148)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x3D18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x3D40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x3D68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x3D90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x3DB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x3DE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x3E08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x3E30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x3E58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x3E80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x3EA8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_61;                   // 0x3ED0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_60;                   // 0x3F60(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_59;                   // 0x3FF0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_58;                   // 0x4080(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_57;                   // 0x4110(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_56;                   // 0x41A0(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_6;                    // 0x4230(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x42E0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_55;                   // 0x4318(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_54;                   // 0x43A8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_53;                   // 0x4438(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_52;                   // 0x44C8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_51;                   // 0x4558(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_50;                   // 0x45E8(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_5;                    // 0x4678(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x4728(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_49;                   // 0x4760(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_48;                   // 0x47F0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_47;                   // 0x4880(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_46;                   // 0x4910(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_45;                   // 0x49A0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_44;                   // 0x4A30(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_4;                    // 0x4AC0(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x4B70(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_43;                   // 0x4BA8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_42;                   // 0x4C38(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_41;                   // 0x4CC8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_40;                   // 0x4D58(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_39;                   // 0x4DE8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_38;                   // 0x4E78(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_3;                    // 0x4F08(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x4FB8(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2_ABP_LiufangzheCommon_C; // 0x4FF0(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x5020(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4_ABP_LiufangzheCommon_C; // 0x5058(0x0148)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x51A0(0x01B0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3_ABP_LiufangzheCommon_C; // 0x5350(0x01B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x5500(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26_ABP_LiufangzheCommon_C; // 0x5528(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25_ABP_LiufangzheCommon_C; // 0x5550(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24_ABP_LiufangzheCommon_C; // 0x5578(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23_ABP_LiufangzheCommon_C; // 0x55A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22_ABP_LiufangzheCommon_C; // 0x55C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21_ABP_LiufangzheCommon_C; // 0x55F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20_ABP_LiufangzheCommon_C; // 0x5618(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19_ABP_LiufangzheCommon_C; // 0x5640(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18_ABP_LiufangzheCommon_C; // 0x5668(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17_ABP_LiufangzheCommon_C; // 0x5690(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16_ABP_LiufangzheCommon_C; // 0x56B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15_ABP_LiufangzheCommon_C; // 0x56E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14_ABP_LiufangzheCommon_C; // 0x5708(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13_ABP_LiufangzheCommon_C; // 0x5730(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12_ABP_LiufangzheCommon_C; // 0x5758(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11_ABP_LiufangzheCommon_C; // 0x5780(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10_ABP_LiufangzheCommon_C; // 0x57A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9_ABP_LiufangzheCommon_C; // 0x57D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8_ABP_LiufangzheCommon_C; // 0x57F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7_ABP_LiufangzheCommon_C; // 0x5820(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6_ABP_LiufangzheCommon_C; // 0x5848(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_37;                   // 0x5870(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_36;                   // 0x5900(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_35;                   // 0x5990(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_3;                   // 0x5A20(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14_ABP_LiufangzheCommon_C; // 0x5AE0(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5_ABP_LiufangzheCommon_C; // 0x5B18(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13_ABP_LiufangzheCommon_C; // 0x5B40(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12_ABP_LiufangzheCommon_C; // 0x5B78(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_34;                   // 0x5BB0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11_ABP_LiufangzheCommon_C; // 0x5C40(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_33;                   // 0x5C78(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10_ABP_LiufangzheCommon_C; // 0x5D08(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_32;                   // 0x5D40(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31;                   // 0x5DD0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_30;                   // 0x5E60(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_2;                   // 0x5EF0(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9_ABP_LiufangzheCommon_C; // 0x5FB0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_29;                   // 0x5FE8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_28;                   // 0x6078(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_27;                   // 0x6108(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_1;                   // 0x6198(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8_ABP_LiufangzheCommon_C; // 0x6258(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4_ABP_LiufangzheCommon_C; // 0x6290(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_26;                   // 0x62B8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25;                   // 0x6348(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24;                   // 0x63D8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23;                   // 0x6468(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22;                   // 0x64F8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x6588(0x0090)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x6618(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7_ABP_LiufangzheCommon_C; // 0x66D8(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1_ABP_LiufangzheCommon_C; // 0x6710(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6_ABP_LiufangzheCommon_C; // 0x6740(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3_ABP_LiufangzheCommon_C; // 0x6778(0x0148)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x68C0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x6950(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x69E0(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x6A70(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x6B00(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x6B90(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_2;                    // 0x6C20(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5_ABP_LiufangzheCommon_C; // 0x6CD0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x6D08(0x0090)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x6D98(0x00D8)()
	struct FAnimNode_MakeDynamicAdditive          AnimGraphNode_MakeDynamicAdditive;                 // 0x6E70(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x6EA8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x6F38(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x6FC8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10_ABP_LiufangzheCommon_C; // 0x7058(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9_ABP_LiufangzheCommon_C; // 0x70E8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8_ABP_LiufangzheCommon_C; // 0x7178(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt_1;                    // 0x7208(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4_ABP_LiufangzheCommon_C; // 0x72B8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2_ABP_LiufangzheCommon_C; // 0x72F0(0x0148)()
	uint8                                         Pad_3202[0x8];                                     // 0x7438(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2_ABP_LiufangzheCommon_C; // 0x7440(0x01B0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2_ABP_LiufangzheCommon_C;       // 0x75F0(0x0060)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_ABP_LiufangzheCommon_C; // 0x7650(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1_ABP_LiufangzheCommon_C;       // 0x7710(0x0060)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1_ABP_LiufangzheCommon_C; // 0x7770(0x01B0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3_ABP_LiufangzheCommon_C; // 0x7920(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2_ABP_LiufangzheCommon_C; // 0x7948(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_ABP_LiufangzheCommon_C;         // 0x7970(0x0060)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7_ABP_LiufangzheCommon_C; // 0x79D0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3_ABP_LiufangzheCommon_C; // 0x7A60(0x0038)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_ABP_LiufangzheCommon_C; // 0x7A98(0x0030)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2_ABP_LiufangzheCommon_C; // 0x7AC8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1_ABP_LiufangzheCommon_C; // 0x7B00(0x0148)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1_ABP_LiufangzheCommon_C; // 0x7C48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_ABP_LiufangzheCommon_C; // 0x7C70(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6_ABP_LiufangzheCommon_C; // 0x7C98(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5_ABP_LiufangzheCommon_C; // 0x7D28(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4_ABP_LiufangzheCommon_C; // 0x7DB8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3_ABP_LiufangzheCommon_C; // 0x7E48(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2_ABP_LiufangzheCommon_C; // 0x7ED8(0x0090)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1_ABP_LiufangzheCommon_C; // 0x7F68(0x0090)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x7FF8(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1_ABP_LiufangzheCommon_C; // 0x80A8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_ABP_LiufangzheCommon_C; // 0x80E0(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_ABP_LiufangzheCommon_C;  // 0x8170(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_ABP_LiufangzheCommon_C; // 0x81A8(0x0148)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_ABP_LiufangzheCommon_C; // 0x82F0(0x01B0)()
	bool                                          ___0;                                              // 0x84A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          _kh_0;                                             // 0x84A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          _0;                                                // 0x84A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Five__0;                                           // 0x84A3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ____0;                                             // 0x84A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	ELiufangzheWeaponType                         Fh__;                                              // 0x84A5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          A__7;                                              // 0x84A6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          A__s;                                              // 0x84A7(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_LiufangzheCommon(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_52C450844EBF9BFBB8282B9C6B941D1D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_C823D0574DC7BFFD1486B185FB74217D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_8E52222C4F7CCA4D8A2BD6955D653104();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_0E3C99E146C38005332675958239B31D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_78BE75ED4C9F1548F6881EA7C9ABF4E3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_6684FE9C458CA18198F2F6869D5F50BC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_6D4A355648553BA8DC9ED5BBD4A5BE4F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_D0E8C1B244BA4AE4F53BDAAB951909F1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_8D24B3C84F11D4FB693B7D8E2C17750E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_D7E7038741792DF8F4A08D844645A02B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_0E45F0A248B5EB834B1D118F89243BA4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_51ACED6F4934CF7F238A3D96E5032A90();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_AE5AEE88411D7A64F1658EB02757165D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_4AC22FD044DE03780A4E2EA42024E95D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_ED42731540984E9B5E52E295CD3D3AFD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_DD3D8D8B4A0C9E8BF8CB268A990B6AB7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_038BD5884F253D75CC75A7B7E01FF7D1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_C94ECA934CA1B69A6B96AFA2CCEDA69E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_734160404187CF651CD4A58A68954FC3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_73A9AE2F422C05AD32CD6E89F9D8FC5D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_E17D8B5545F0B8950DC1E685D29CA41E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_44F768BE4EF62984DC660CA208794E4C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_8BCEBEFD4E80ABEED11F33AEBBE8E07A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_B859894D4196260BB9D990B58667D389();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_91D6953F49819543EB80E18778493B28();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_5698CF474CA398956D5F57A24D8EAF21();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_2E6E0A0341F76826D3A50B9B86F40869();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_27B9F7744E79632838E7D493A59E1DF8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_653B74A24B3267FB601126A104B583E0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_166E975E48E756AB32647B922F7B4BAF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_C9529B2F4415C6A3301735A1EAD298B6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_FB6C909D404D38CD70FD1DA55BF02B92();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByEnum_4D5E93AC4629E6DC859AF3B0A0F9D354();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_E285C5B644D0C7EDEB0867BB1A35D376();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByEnum_72B4CE36439BDF09C516EBAD9CF35D7A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByEnum_3BBA761A42B361B1F14869BFC89E77AF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_TransitionResult_2A58B9C64010468AE65A28A34150184F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByEnum_32D266954799444979DCA3B3A94543CF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_0165AE4B44D6CA5FC416FEA0ABD19225();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_C904936E4A91604CE61911B883E94EAD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BlendListByInt_79A63DAC4F1506CACEC0A5829047958E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_Feedback_1110F51F47BAC0E6EDD68BB579A50C8A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_LiufangzheCommon_AnimGraphNode_BoneRotateToLocation_1980760A423198CC6ADEF49705FC9B54();
	void IKAndFk_Clone(const struct FPoseLink& InPose, struct FPoseLink* Param_IKAndFk_Clone);
	void ______Tag();
	void AnimGraph(struct FPoseLink* Param_AnimGraph);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_LiufangzheCommon_C">();
	}
	static class UABP_LiufangzheCommon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_LiufangzheCommon_C>();
	}
};
static_assert(alignof(UABP_LiufangzheCommon_C) == 0x000010, "Wrong alignment on UABP_LiufangzheCommon_C");
static_assert(sizeof(UABP_LiufangzheCommon_C) == 0x0084B0, "Wrong size on UABP_LiufangzheCommon_C");
static_assert(offsetof(UABP_LiufangzheCommon_C, UberGraphFrame_ABP_LiufangzheCommon_C) == 0x002E88, "Member 'UABP_LiufangzheCommon_C::UberGraphFrame_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Root_1_ABP_LiufangzheCommon_C) == 0x002E90, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Root_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_LocalToComponentSpace_ABP_LiufangzheCommon_C) == 0x002EC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_LocalToComponentSpace_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_ComponentToLocalSpace_ABP_LiufangzheCommon_C) == 0x002EE8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_ComponentToLocalSpace_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Feedback_ABP_LiufangzheCommon_C) == 0x002F08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Feedback_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SightLock_ABP_LiufangzheCommon_C) == 0x003170, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SightLock_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_LinkedInputPose_ABP_LiufangzheCommon_C) == 0x003330, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_LinkedInputPose_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BoneRotateToLocation_ABP_LiufangzheCommon_C) == 0x003468, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BoneRotateToLocation_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Root_ABP_LiufangzheCommon_C) == 0x003590, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Root_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_44) == 0x0035C8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_44' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_43) == 0x0035F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_43' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_42) == 0x003618, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_42' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_41) == 0x003640, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_41' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_40) == 0x003668, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_40' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_39) == 0x003690, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_39' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_4) == 0x0036B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_22) == 0x0036E8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_22' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_67) == 0x003720, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_67' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_66) == 0x0037B0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_66' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_65) == 0x003840, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_65' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_64) == 0x0038D0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_64' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_63) == 0x003960, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_63' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_62) == 0x0039F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_62' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_7) == 0x003A80, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_7' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_21) == 0x003B30, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_21' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_3_ABP_LiufangzheCommon_C) == 0x003B68, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_20) == 0x003B98, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_20' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_5) == 0x003BD0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_5' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_38) == 0x003D18, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_38' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_37) == 0x003D40, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_37' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_36) == 0x003D68, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_36' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_35) == 0x003D90, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_35' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_34) == 0x003DB8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_34' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_33) == 0x003DE0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_33' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_32) == 0x003E08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_32' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_31) == 0x003E30, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_30) == 0x003E58, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_29) == 0x003E80, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_28) == 0x003EA8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_61) == 0x003ED0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_61' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_60) == 0x003F60, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_60' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_59) == 0x003FF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_59' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_58) == 0x004080, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_58' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_57) == 0x004110, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_57' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_56) == 0x0041A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_56' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_6) == 0x004230, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_6' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_19) == 0x0042E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_19' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_55) == 0x004318, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_55' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_54) == 0x0043A8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_54' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_53) == 0x004438, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_53' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_52) == 0x0044C8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_52' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_51) == 0x004558, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_51' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_50) == 0x0045E8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_50' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_5) == 0x004678, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_5' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_18) == 0x004728, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_18' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_49) == 0x004760, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_49' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_48) == 0x0047F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_48' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_47) == 0x004880, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_47' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_46) == 0x004910, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_46' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_45) == 0x0049A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_45' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_44) == 0x004A30, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_44' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_4) == 0x004AC0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_4' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_17) == 0x004B70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_17' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_43) == 0x004BA8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_43' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_42) == 0x004C38, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_42' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_41) == 0x004CC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_41' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_40) == 0x004D58, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_40' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_39) == 0x004DE8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_39' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_38) == 0x004E78, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_38' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_3) == 0x004F08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_3' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_16) == 0x004FB8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_16' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_2_ABP_LiufangzheCommon_C) == 0x004FF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_15) == 0x005020, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_15' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_4_ABP_LiufangzheCommon_C) == 0x005058, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_4) == 0x0051A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_3_ABP_LiufangzheCommon_C) == 0x005350, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_27) == 0x005500, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_26_ABP_LiufangzheCommon_C) == 0x005528, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_26_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_25_ABP_LiufangzheCommon_C) == 0x005550, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_25_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_24_ABP_LiufangzheCommon_C) == 0x005578, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_24_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_23_ABP_LiufangzheCommon_C) == 0x0055A0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_23_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_22_ABP_LiufangzheCommon_C) == 0x0055C8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_22_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_21_ABP_LiufangzheCommon_C) == 0x0055F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_21_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_20_ABP_LiufangzheCommon_C) == 0x005618, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_20_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_19_ABP_LiufangzheCommon_C) == 0x005640, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_19_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_18_ABP_LiufangzheCommon_C) == 0x005668, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_18_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_17_ABP_LiufangzheCommon_C) == 0x005690, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_17_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_16_ABP_LiufangzheCommon_C) == 0x0056B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_16_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_15_ABP_LiufangzheCommon_C) == 0x0056E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_15_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_14_ABP_LiufangzheCommon_C) == 0x005708, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_14_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_13_ABP_LiufangzheCommon_C) == 0x005730, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_13_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_12_ABP_LiufangzheCommon_C) == 0x005758, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_12_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_11_ABP_LiufangzheCommon_C) == 0x005780, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_11_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_10_ABP_LiufangzheCommon_C) == 0x0057A8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_10_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_9_ABP_LiufangzheCommon_C) == 0x0057D0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_9_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_8_ABP_LiufangzheCommon_C) == 0x0057F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_8_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_7_ABP_LiufangzheCommon_C) == 0x005820, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_7_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_6_ABP_LiufangzheCommon_C) == 0x005848, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_6_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_37) == 0x005870, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_37' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_36) == 0x005900, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_36' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_35) == 0x005990, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_35' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_3) == 0x005A20, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_3' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_14_ABP_LiufangzheCommon_C) == 0x005AE0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_14_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_5_ABP_LiufangzheCommon_C) == 0x005B18, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_5_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_13_ABP_LiufangzheCommon_C) == 0x005B40, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_13_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_12_ABP_LiufangzheCommon_C) == 0x005B78, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_12_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_34) == 0x005BB0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_34' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_11_ABP_LiufangzheCommon_C) == 0x005C40, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_11_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_33) == 0x005C78, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_33' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_10_ABP_LiufangzheCommon_C) == 0x005D08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_10_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_32) == 0x005D40, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_32' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_31) == 0x005DD0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_31' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_30) == 0x005E60, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_30' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_2) == 0x005EF0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_2' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_9_ABP_LiufangzheCommon_C) == 0x005FB0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_9_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_29) == 0x005FE8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_29' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_28) == 0x006078, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_28' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_27) == 0x006108, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_27' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum_1) == 0x006198, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum_1' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_8_ABP_LiufangzheCommon_C) == 0x006258, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_8_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_4_ABP_LiufangzheCommon_C) == 0x006290, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_26) == 0x0062B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_26' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_25) == 0x006348, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_25' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_24) == 0x0063D8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_24' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_23) == 0x006468, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_23' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_22) == 0x0064F8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_22' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_21) == 0x006588, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_21' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByEnum) == 0x006618, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_7_ABP_LiufangzheCommon_C) == 0x0066D8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_7_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_1_ABP_LiufangzheCommon_C) == 0x006710, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_6_ABP_LiufangzheCommon_C) == 0x006740, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_6_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_3_ABP_LiufangzheCommon_C) == 0x006778, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_20) == 0x0068C0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_19) == 0x006950, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_18) == 0x0069E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_17) == 0x006A70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_16) == 0x006B00, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_15) == 0x006B90, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_2) == 0x006C20, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_2' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_5_ABP_LiufangzheCommon_C) == 0x006CD0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_5_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_14) == 0x006D08, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_ApplyAdditive) == 0x006D98, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_MakeDynamicAdditive) == 0x006E70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_MakeDynamicAdditive' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_13) == 0x006EA8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_12) == 0x006F38, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_11) == 0x006FC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_10_ABP_LiufangzheCommon_C) == 0x007058, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_10_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_9_ABP_LiufangzheCommon_C) == 0x0070E8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_9_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_8_ABP_LiufangzheCommon_C) == 0x007178, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_8_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt_1) == 0x007208, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt_1' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_4_ABP_LiufangzheCommon_C) == 0x0072B8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_2_ABP_LiufangzheCommon_C) == 0x0072F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_2_ABP_LiufangzheCommon_C) == 0x007440, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Slot_2_ABP_LiufangzheCommon_C) == 0x0075F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Slot_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_LinkedAnimLayer_ABP_LiufangzheCommon_C) == 0x007650, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_LinkedAnimLayer_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Slot_1_ABP_LiufangzheCommon_C) == 0x007710, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Slot_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_1_ABP_LiufangzheCommon_C) == 0x007770, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_3_ABP_LiufangzheCommon_C) == 0x007920, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_2_ABP_LiufangzheCommon_C) == 0x007948, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_Slot_ABP_LiufangzheCommon_C) == 0x007970, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_Slot_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_7_ABP_LiufangzheCommon_C) == 0x0079D0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_7_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_3_ABP_LiufangzheCommon_C) == 0x007A60, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_UseCachedPose_ABP_LiufangzheCommon_C) == 0x007A98, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_UseCachedPose_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_2_ABP_LiufangzheCommon_C) == 0x007AC8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_1_ABP_LiufangzheCommon_C) == 0x007B00, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_1_ABP_LiufangzheCommon_C) == 0x007C48, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_TransitionResult_ABP_LiufangzheCommon_C) == 0x007C70, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_TransitionResult_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_6_ABP_LiufangzheCommon_C) == 0x007C98, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_6_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_5_ABP_LiufangzheCommon_C) == 0x007D28, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_5_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_4_ABP_LiufangzheCommon_C) == 0x007DB8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_4_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_3_ABP_LiufangzheCommon_C) == 0x007E48, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_3_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_2_ABP_LiufangzheCommon_C) == 0x007ED8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_2_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_1_ABP_LiufangzheCommon_C) == 0x007F68, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_BlendListByInt) == 0x007FF8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_BlendListByInt' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_1_ABP_LiufangzheCommon_C) == 0x0080A8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_1_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SequencePlayer_ABP_LiufangzheCommon_C) == 0x0080E0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SequencePlayer_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateResult_ABP_LiufangzheCommon_C) == 0x008170, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateResult_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_StateMachine_ABP_LiufangzheCommon_C) == 0x0081A8, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_StateMachine_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, AnimGraphNode_SaveCachedPose_ABP_LiufangzheCommon_C) == 0x0082F0, "Member 'UABP_LiufangzheCommon_C::AnimGraphNode_SaveCachedPose_ABP_LiufangzheCommon_C' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, ___0) == 0x0084A0, "Member 'UABP_LiufangzheCommon_C::___0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, _kh_0) == 0x0084A1, "Member 'UABP_LiufangzheCommon_C::_kh_0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, _0) == 0x0084A2, "Member 'UABP_LiufangzheCommon_C::_0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, Five__0) == 0x0084A3, "Member 'UABP_LiufangzheCommon_C::Five__0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, ____0) == 0x0084A4, "Member 'UABP_LiufangzheCommon_C::____0' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, Fh__) == 0x0084A5, "Member 'UABP_LiufangzheCommon_C::Fh__' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, A__7) == 0x0084A6, "Member 'UABP_LiufangzheCommon_C::A__7' has a wrong offset!");
static_assert(offsetof(UABP_LiufangzheCommon_C, A__s) == 0x0084A7, "Member 'UABP_LiufangzheCommon_C::A__s' has a wrong offset!");

}

