#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SoarWing

#include "Basic.hpp"

#include "ABP_SoarWing_classes.hpp"
#include "ABP_SoarWing_parameters.hpp"


namespace SDK
{

// Function ABP_SoarWing.ABP_SoarWing_C.ExecuteUbergraph_ABP_SoarWing
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_SoarWing_C::ExecuteUbergraph_ABP_SoarWing(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SoarWing_C", "ExecuteUbergraph_ABP_SoarWing");

	Params::ABP_SoarWing_C_ExecuteUbergraph_ABP_SoarWing Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_SoarWing.ABP_SoarWing_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_SoarWing_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SoarWing_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SoarWing.ABP_SoarWing_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_SoarWing_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SoarWing_C", "BlueprintUpdateAnimation");

	Params::ABP_SoarWing_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_SoarWing.ABP_SoarWing_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SoarWing_AnimGraphNode_TransitionResult_362C454640BFED117D9E3A94E5654B0E
// (BlueprintEvent)

void UABP_SoarWing_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SoarWing_AnimGraphNode_TransitionResult_362C454640BFED117D9E3A94E5654B0E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SoarWing_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SoarWing_AnimGraphNode_TransitionResult_362C454640BFED117D9E3A94E5654B0E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_SoarWing.ABP_SoarWing_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UABP_SoarWing_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_SoarWing_C", "AnimGraph");

	Params::ABP_SoarWing_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

