#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ani_UiView_Inventory_Xin1_Close03

#include "Basic.hpp"

#include "Ani_UiView_Inventory_Xin1_Close03_classes.hpp"
#include "Ani_UiView_Inventory_Xin1_Close03_parameters.hpp"


namespace SDK
{

// Function Ani_UiView_Inventory_Xin1_Close03.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                PnlCaptionList                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_UiView_Inventory_Xin1_Close03::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0(class AUIContainerActor* PnlCaptionList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 Parms{};

	Parms.PnlCaptionList = PnlCaptionList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_UiView_Inventory_Xin1_Close03.SequenceDirector_C.PnlCaptionList_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                PnlCaptionList                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_UiView_Inventory_Xin1_Close03::USequenceDirector_C::PnlCaptionList_Event_0(class AUIContainerActor* PnlCaptionList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "PnlCaptionList_Event_0");

	Params::SequenceDirector_C_PnlCaptionList_Event_0 Parms{};

	Parms.PnlCaptionList = PnlCaptionList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_UiView_Inventory_Xin1_Close03.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_UiView_Inventory_Xin1_Close03::USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

