#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ani_Ui_ItemBaseA_DtoS

#include "Basic.hpp"

#include "Ani_Ui_ItemBaseA_DtoS_classes.hpp"
#include "Ani_Ui_ItemBaseA_DtoS_parameters.hpp"


namespace SDK
{

// Function Ani_Ui_ItemBaseA_DtoS.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_ItemBaseA                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_Ui_ItemBaseA_DtoS::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_1(class AUIContainerActor* UiItem_ItemBaseA)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_1");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1 Parms{};

	Parms.UiItem_ItemBaseA = UiItem_ItemBaseA;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_Ui_ItemBaseA_DtoS.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_ItemBaseA                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_Ui_ItemBaseA_DtoS::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0(class AUIContainerActor* UiItem_ItemBaseA)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 Parms{};

	Parms.UiItem_ItemBaseA = UiItem_ItemBaseA;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_Ui_ItemBaseA_DtoS.SequenceDirector_C.Stop
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_ItemBaseA                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_Ui_ItemBaseA_DtoS::USequenceDirector_C::Stop(class AUIContainerActor* UiItem_ItemBaseA)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "Stop");

	Params::SequenceDirector_C_Stop Parms{};

	Parms.UiItem_ItemBaseA = UiItem_ItemBaseA;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_Ui_ItemBaseA_DtoS.SequenceDirector_C.Select
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_ItemBaseA                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_Ui_ItemBaseA_DtoS::USequenceDirector_C::Select(class AUIContainerActor* UiItem_ItemBaseA)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "Select");

	Params::SequenceDirector_C_Select Parms{};

	Parms.UiItem_ItemBaseA = UiItem_ItemBaseA;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_Ui_ItemBaseA_DtoS.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_Ui_ItemBaseA_DtoS::USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

