#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ani_UiView_Inventory_Xin1_start15

#include "Basic.hpp"

#include "Ani_UiView_Inventory_Xin1_start15_classes.hpp"
#include "Ani_UiView_Inventory_Xin1_start15_parameters.hpp"


namespace SDK
{

// Function Ani_UiView_Inventory_Xin1_start15.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                PnlCaptionList                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_UiView_Inventory_Xin1_start15::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_1(class AUIContainerActor* PnlCaptionList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_1");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1 Parms{};

	Parms.PnlCaptionList = PnlCaptionList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_UiView_Inventory_Xin1_start15.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)

void Ani_UiView_Inventory_Xin1_start15::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ani_UiView_Inventory_Xin1_start15.SequenceDirector_C.SequenceEvent_0
// (BlueprintCallable, BlueprintEvent)

void Ani_UiView_Inventory_Xin1_start15::USequenceDirector_C::SequenceEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ani_UiView_Inventory_Xin1_start15.SequenceDirector_C.PnlCaptionList_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                PnlCaptionList                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_UiView_Inventory_Xin1_start15::USequenceDirector_C::PnlCaptionList_Event_0(class AUIContainerActor* PnlCaptionList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "PnlCaptionList_Event_0");

	Params::SequenceDirector_C_PnlCaptionList_Event_0 Parms{};

	Parms.PnlCaptionList = PnlCaptionList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_UiView_Inventory_Xin1_start15.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_UiView_Inventory_Xin1_start15::USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

