#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NA010

#include "Basic.hpp"

#include "BP_BaseBird_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NA010.BP_NA010_C
// 0x0010 (0x07C0 - 0x07B0)
class ABP_NA010_C final : public ABP_BaseBird_C
{
public:
	class UCapsuleComponent*                      Root;                                              // 0x07B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NA010_C">();
	}
	static class ABP_NA010_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NA010_C>();
	}
};
static_assert(alignof(ABP_NA010_C) == 0x000010, "Wrong alignment on ABP_NA010_C");
static_assert(sizeof(ABP_NA010_C) == 0x0007C0, "Wrong size on ABP_NA010_C");
static_assert(offsetof(ABP_NA010_C, Root) == 0x0007B0, "Member 'ABP_NA010_C::Root' has a wrong offset!");

}

