#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Nanzhu_SP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Nanzhu_SP.GA_Nanzhu_SP_C
// 0x0008 (0x0560 - 0x0558)
class UGA_Nanzhu_SP_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Nanzhu_SP_C;                     // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Nanzhu_SP(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnCompleted_5D118C384AE61F1C80292E8169A45329();
	void OnBlendOut_5D118C384AE61F1C80292E8169A45329();
	void OnInterrupted_5D118C384AE61F1C80292E8169A45329();
	void OnCancelled_5D118C384AE61F1C80292E8169A45329();
	void OnTick_5D118C384AE61F1C80292E8169A45329();
	void OnCompleted_5D118C384AE61F1C80292E81D617D4B4();
	void OnBlendOut_5D118C384AE61F1C80292E81D617D4B4();
	void OnInterrupted_5D118C384AE61F1C80292E81D617D4B4();
	void OnCancelled_5D118C384AE61F1C80292E81D617D4B4();
	void OnTick_5D118C384AE61F1C80292E81D617D4B4();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Nanzhu_SP_C">();
	}
	static class UGA_Nanzhu_SP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Nanzhu_SP_C>();
	}
};
static_assert(alignof(UGA_Nanzhu_SP_C) == 0x000008, "Wrong alignment on UGA_Nanzhu_SP_C");
static_assert(sizeof(UGA_Nanzhu_SP_C) == 0x000560, "Wrong size on UGA_Nanzhu_SP_C");
static_assert(offsetof(UGA_Nanzhu_SP_C, UberGraphFrame_GA_Nanzhu_SP_C) == 0x000558, "Member 'UGA_Nanzhu_SP_C::UberGraphFrame_GA_Nanzhu_SP_C' has a wrong offset!");

}

