#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Nanzhu_SP

#include "Basic.hpp"

#include "GA_Nanzhu_SP_classes.hpp"
#include "GA_Nanzhu_SP_parameters.hpp"


namespace SDK
{

// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.ExecuteUbergraph_GA_Nanzhu_SP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Nanzhu_SP_C::ExecuteUbergraph_GA_Nanzhu_SP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "ExecuteUbergraph_GA_Nanzhu_SP");

	Params::GA_Nanzhu_SP_C_ExecuteUbergraph_GA_Nanzhu_SP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Nanzhu_SP_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnCompleted_5D118C384AE61F1C80292E8169A45329
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnCompleted_5D118C384AE61F1C80292E8169A45329()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnCompleted_5D118C384AE61F1C80292E8169A45329");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnBlendOut_5D118C384AE61F1C80292E8169A45329
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnBlendOut_5D118C384AE61F1C80292E8169A45329()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnBlendOut_5D118C384AE61F1C80292E8169A45329");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnInterrupted_5D118C384AE61F1C80292E8169A45329
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnInterrupted_5D118C384AE61F1C80292E8169A45329()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnInterrupted_5D118C384AE61F1C80292E8169A45329");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnCancelled_5D118C384AE61F1C80292E8169A45329
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnCancelled_5D118C384AE61F1C80292E8169A45329()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnCancelled_5D118C384AE61F1C80292E8169A45329");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnTick_5D118C384AE61F1C80292E8169A45329
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnTick_5D118C384AE61F1C80292E8169A45329()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnTick_5D118C384AE61F1C80292E8169A45329");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnCompleted_5D118C384AE61F1C80292E81D617D4B4
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnCompleted_5D118C384AE61F1C80292E81D617D4B4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnCompleted_5D118C384AE61F1C80292E81D617D4B4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnBlendOut_5D118C384AE61F1C80292E81D617D4B4
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnBlendOut_5D118C384AE61F1C80292E81D617D4B4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnBlendOut_5D118C384AE61F1C80292E81D617D4B4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnInterrupted_5D118C384AE61F1C80292E81D617D4B4
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnInterrupted_5D118C384AE61F1C80292E81D617D4B4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnInterrupted_5D118C384AE61F1C80292E81D617D4B4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnCancelled_5D118C384AE61F1C80292E81D617D4B4
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnCancelled_5D118C384AE61F1C80292E81D617D4B4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnCancelled_5D118C384AE61F1C80292E81D617D4B4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Nanzhu_SP.GA_Nanzhu_SP_C.OnTick_5D118C384AE61F1C80292E81D617D4B4
// (BlueprintCallable, BlueprintEvent)

void UGA_Nanzhu_SP_C::OnTick_5D118C384AE61F1C80292E81D617D4B4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Nanzhu_SP_C", "OnTick_5D118C384AE61F1C80292E81D617D4B4");

	UObject::ProcessEvent(Func, nullptr);
}

}

